---
title: "Conv 2019"
date: 2020-03-07T10:33:30+08:00
draft: true
author: "北河沿"
type: "post"
categories: 
 - R
 
description: "疫情的数据R包运用"
# summary: ""
---

稍微读了一下源代码，理解了语言是如何影响到数据的。还是中文的更好。

先做一些准备工作，下载remotes这个包
```{r}
# prepare for remote 
# install.packages("remotes")
# library(remotes)
```
用remotes安装GuangchuangYu发布在github上的R包：nCov2019

```{r}
# install the package
# remotes::install_github("/nCov2019")
# library(nCov2019)
```

显示一些数据结构
```{r}
# load latest data
Sys.setlocale("LC_ALL", locale="zh_CN.UTF-8")
library(nCov2019)
library(tidyverse)
x <- get_nCov2019(lang = "zh")

# show the total number
x

# updated time
time(x)
```

```{r}
# open browser 
# open(x)

# list different provinces
#Sys.setlocale("LC_ALL", locale="zh_CN.UTF-8")
# library(nCov2019)
# x <- get_nCov2019()
x[]
```

```{r}
#
# library(nCov2019)
# x <- get_nCov2019()
x["湖北"]

```

```{r}
#library(nCov2019)
# library(ggplot2)
#x <- get_nCov2019()
b <- x['北京']
b
ggplot(b, aes(name, confirm)) + 
  geom_bar(stat = "identity", fill = "pink") + 
  xlab("城区") + 
  ylab("确诊人数") +
  theme_classic()+
theme(text = element_text(family = "STHeiti"))   # must be the last one to be sure the right font is oused. 

```

```{r}
# newly 
# library(tidyverse)
# library(nCov2019)
# x <- get_nCov2019()

d = x['global',] %>% filter(name != '中国')
d$confirm=as.numeric(d$confirm)

d$name = fct_reorder(d$name, d$confirm)

ggplot(d, aes(name, confirm)) +
  geom_col(fill='orange', width = 0.8) + 
  coord_flip() +
  geom_text(aes(y = confirm+2, label=confirm),size=2, hjust=0) +
  theme_minimal(base_size=10) +
 
  xlab(NULL) + ylab(NULL)+
theme(text = element_text(family = "STHeiti")) 
```

```{r}
# another plot
# library(nCov2019)
# library(ggplot2)
# x <- get_nCov2019()
ggplot(summary(x), aes(as.Date(date, "%m.%d"), as.numeric(confirm))) +
  geom_col(fill='firebrick') + theme_minimal(base_size = 14) +
  xlab(NULL) + ylab(NULL) +
  labs(caption = paste("更新时间:", time(x))) +
  theme(text = element_text(family = "STHeiti")) 
```